spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 7777
  servlet:
    context-path: /ilead

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
